{{- if and .Values.securityContextConstraints.enabled (empty .Values.controller.existingScc) -}}
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: {{ include "ingress-nginx.fullname" . }}
  labels:
    {{- include "ingress-nginx.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller

allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false

allowPrivilegeEscalation: true

allowPrivilegedContainer: false
allowedCapabilities:
- NET_BIND_SERVICE 
requiredDropCapabilities:
- ALL
fsGroup:
  type: MustRunAs

priority: null
readOnlyRootFilesystem: false
runAsUser:
  type: MustRunAsNonRoot
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny

volumes:
- configMap
- downwardAPI
- emptyDir
- projected
- secret
{{- end }}